---
title: "Senior Thesis Work"
author: "Riva"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

```{r data, message=FALSE}
library('yaml')  
library('knitr')

```
1. Join together all the gtfs datasets (trips, transfers, etc)
```{r, message=FALSE}
source("join_gtfs.R", chdir = TRUE)
kable(head(sample(trips, size = 10)))
kable(filter(trips, from_id == 's104'))
```
2. Extract names from the raw data for easy matching.
```{sh get_names}
cat turnstile_data/turnstile*.txt | cut -d, -f4 | sort | uniq > turnstile_names.txt
cat station_ids_trips.csv | cut -d, -f4 | sort | uniq > gtfs_names.txt
```
3. Run match_names.py to put everything in a mergetable.
```{python match_names}
import match_names
```
4. Small manual edits to get everything tightened up.
```{sh small_edits}
awk -f smalleredits.awk
```
5. Merge everything.
```{r, message=FALSE}
source("merge.R")
```
```{r, message=FALSE}
source("load_subway_trips.R")
```
```{r daily, message=FALSE}
source("DailyGraphs.R")
```
